/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zidun
 */
public class admin_user extends javax.swing.JFrame {
     public Statement st;
    public ResultSet rs;
    public Connection cn = config.koneksi.getKoneksi();
    public DefaultTableModel tabmodel;
    public static String session;
    fungsi aksi = new fungsi();
    
    public void judul(){
        Object[] judul ={"No.","Kode User","Nama","Alamat","Email","No.Hp","Username","Jabatan"};
        tabmodel = new DefaultTableModel(null,judul);
        tbl_user.setModel(tabmodel);
    }
    
    
    public void tampildata(){
        try {
            int no = 1;
            st = cn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tbl_user WHERE username != '"+session+"'");
            while (rs.next()) {
                    int b = no++;
                    Object[] data = {
                        b,
                        rs.getInt("kd_user"),
                        rs.getString("nama"),
                        rs.getString("alamat"),
                        rs.getString("email"),
                        rs.getString("no_hp"),
                        rs.getString("username"),
                        rs.getString("jabatan")
                    };
                    tabmodel.addRow(data);           
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
     public void reset(){
        tnama.setText("");
        talamat.setText("");
        temail.setText("");
        tno.setText("");
        tpass.setText("");
        tuser.setText("");
        tuser.setEditable(true);
        bhapus.setVisible(false);
        bedit.setVisible(false);
        bsimpan.setVisible(true);
        breset.setVisible(true);
        tnama.requestFocus();
    }
     
    
//    public void aksi(String sql, String pesan){
//        try {
//            st = cn.createStatement();
//            st.executeUpdate(sql);
//            JOptionPane.showMessageDialog(null, pesan);
//            tampildata();
//            reset();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
     
     public void refresh(){
         tampildata();
         reset();
     }
    /**
     * Creates new form admin_user
     */
    public admin_user() {
        initComponents();
        judul();
        tampildata();
        reset();
        tnama.requestFocus();
        bhapus.setVisible(false);
        bedit.setVisible(false);
        bsimpan.setVisible(true);
        breset.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        tcari = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_user = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        bhapus = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        breset = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        bedit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tno = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        tnama = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        tpass = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        tjabatan = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        hide = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(85, 153, 142));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 610, 20));

        jLabel6.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rmdnzdn");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, -1, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 710, 610, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 146, 61));
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 320, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(232, 146, 61));
        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        temail.setBackground(new java.awt.Color(85, 153, 142));
        temail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        temail.setForeground(new java.awt.Color(255, 255, 255));
        temail.setBorder(null);
        temail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                temailKeyTyped(evt);
            }
        });
        jPanel1.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 320, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 320, 10));

        tcari.setBackground(new java.awt.Color(85, 153, 142));
        tcari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tcari.setForeground(new java.awt.Color(255, 255, 255));
        tcari.setBorder(null);
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });
        jPanel1.add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 560, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(232, 146, 61));
        jLabel12.setText("Pencarian");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 560, 20));

        tbl_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_user);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 690, 420));

        jPanel6.setBackground(new java.awt.Color(74, 131, 122));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("REFRESH");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 120, 40));

        bhapus.setBackground(new java.awt.Color(74, 131, 122));
        bhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhapus.setEnabled(false);
        bhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bhapusMouseClicked(evt);
            }
        });
        bhapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("HAPUS");
        bhapus.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 50));

        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 320, -1));

        breset.setBackground(new java.awt.Color(74, 131, 122));
        breset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        breset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bresetMouseClicked(evt);
            }
        });
        breset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("RESET");
        breset.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 50));

        jPanel1.add(breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 320, -1));

        bsimpan.setBackground(new java.awt.Color(74, 131, 122));
        bsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsimpanMouseClicked(evt);
            }
        });
        bsimpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SIMPAN");
        bsimpan.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 50));

        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 320, 50));

        bedit.setBackground(new java.awt.Color(74, 131, 122));
        bedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bedit.setEnabled(false);
        bedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beditMouseClicked(evt);
            }
        });
        bedit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("UBAH");
        bedit.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 50));

        jPanel1.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 320, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(232, 146, 61));
        jLabel14.setText("No Handphone");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        tno.setBackground(new java.awt.Color(85, 153, 142));
        tno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tno.setForeground(new java.awt.Color(255, 255, 255));
        tno.setBorder(null);
        tno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnoKeyTyped(evt);
            }
        });
        jPanel1.add(tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 320, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 320, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(232, 146, 61));
        jLabel15.setText("Username");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        tuser.setBackground(new java.awt.Color(85, 153, 142));
        tuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tuser.setForeground(new java.awt.Color(255, 255, 255));
        tuser.setBorder(null);
        tuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tuserKeyTyped(evt);
            }
        });
        jPanel1.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 320, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 320, 10));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(232, 146, 61));
        jLabel19.setText("Password");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 320, 10));

        tnama.setBackground(new java.awt.Color(85, 153, 142));
        tnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tnama.setForeground(new java.awt.Color(255, 255, 255));
        tnama.setBorder(null);
        jPanel1.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 320, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 320, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(232, 146, 61));
        jLabel10.setText("Nama");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        talamat.setBackground(new java.awt.Color(85, 153, 142));
        talamat.setColumns(20);
        talamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        talamat.setForeground(new java.awt.Color(255, 255, 255));
        talamat.setRows(5);
        talamat.setBorder(null);
        jScrollPane2.setViewportView(talamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 320, 80));

        tpass.setBackground(new java.awt.Color(85, 153, 142));
        tpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setBorder(null);
        jPanel1.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 320, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(232, 146, 61));
        jLabel20.setText("Jabatan");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 320, 10));

        tjabatan.setBackground(new java.awt.Color(85, 153, 142));
        tjabatan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tjabatan.setForeground(new java.awt.Color(255, 255, 255));
        tjabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---------------Pilih Jabatan-------------", "admin", "agen", "direktur" }));
        jPanel1.add(tjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 320, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1370, -1));

        jPanel2.setBackground(new java.awt.Color(74, 131, 122));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FORM INPUT USER");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 40));

        hide.setBackground(new java.awt.Color(74, 131, 122));
        hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        hide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kembali");
        hide.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        getContentPane().add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 130, 40));

        close.setBackground(new java.awt.Color(74, 131, 122));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        close.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 50, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temailKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_temailKeyTyped

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        // TODO add your handling code here:
       try {
            int no = 1;
            st = cn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tbl_user WHERE kd_user LIKE '%"+tcari.getText()+"%' OR kd_user LIKE '%"+tcari.getText()+"%' OR nama LIKE '%"+tcari.getText()+"%' OR alamat LIKE '%"+tcari.getText()+"%' OR email LIKE '%"+tcari.getText()+"%' OR no_hp LIKE '%"+tcari.getText()+"%' OR username LIKE '%"+tcari.getText()+"%' OR password LIKE '%"+tcari.getText()+"%' OR jabatan LIKE '%"+tcari.getText()+"%'");
            while (rs.next()) {
                if (rs.getString("username") != session ) {
                    int b = no++;
                    Object[] data = {
                        b,
                        rs.getInt("kd_user"),
                        rs.getString("nama"),
                        rs.getString("alamat"),
                        rs.getString("email"),
                        rs.getString("no_hp"),
                        rs.getString("username"),
                        rs.getString("jabatan")
                    };
                    tabmodel.addRow(data);
                }
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tcariKeyReleased

    private void tbl_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_userMouseClicked
        // TODO add your handling code here:
        tnama.setText(tabmodel.getValueAt(tbl_user.getSelectedRow(), 2)+"");
        temail.setText(tabmodel.getValueAt(tbl_user.getSelectedRow(), 4)+"");
        tno.setText(tabmodel.getValueAt(tbl_user.getSelectedRow(), 5)+"");
        tuser.setText(tabmodel.getValueAt(tbl_user.getSelectedRow(), 6)+"");
        tpass.setText(tabmodel.getValueAt(tbl_user.getSelectedRow(), 7)+"");
        talamat.setText(tabmodel.getValueAt(tbl_user.getSelectedRow(), 3)+"");
        tnama.requestFocus();
        tuser.setEditable(false);
        bhapus.setVisible(true);
        bedit.setVisible(true);
        bsimpan.setVisible(false);
        breset.setVisible(true);
    }//GEN-LAST:event_tbl_userMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        tcariKeyReleased(null);
        tcari.setText("");
        tampildata();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void bhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhapusMouseClicked
        // TODO add your handling code here:
        int jawab = 0;
        if((jawab = JOptionPane.showConfirmDialog(null, "Anda yakin kan menghapus data ini ?","Konfirmasi", JOptionPane.YES_NO_OPTION))==0){
            aksi.hapus("tbl_user", "kd_user = '"+tabmodel.getValueAt(tbl_user.getSelectedRow(), 1)+"'");
            refresh();
//            String sql = "DELETE FROM tbl_user WHERE kd_user = '"+tabmodel.getValueAt(tbl_user.getSelectedRow(), 1)+"'";
//            aksi(sql,"Data Berhasil Dihapus");
        }
    }//GEN-LAST:event_bhapusMouseClicked

    private void bresetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bresetMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bresetMouseClicked

    private void bsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsimpanMouseClicked
        // TODO add your handling code here:
       if(tuser.getText().isEmpty() || tnama.getText().isEmpty() || temail.getText().isEmpty() || tno.getText().isEmpty() || talamat.getText().isEmpty() || tpass.getText().isEmpty() || temail.getText().isEmpty() || tjabatan.getSelectedItem().equals("---------------Pilih Jabatan-------------")){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Terlebih Dahulu");
        } else {
           aksi.simpan("tbl_user","null,'"+tnama.getText()+"','"+talamat.getText()+"','"+temail.getText()+"','"+tno.getText()+"','"+tuser.getText()+"','"+tpass.getText()+"','"+tjabatan.getSelectedItem()+"'");
           refresh();
//            String sql = "INSERT INTO tbl_user VALUES(null,'"+tnama.getText()+"','"+talamat.getText()+"','"+temail.getText()+"','"+tno.getText()+"','"+tuser.getText()+"','"+tpass.getText()+"','"+tjabatan.getSelectedItem()+"')";
//            aksi(sql,"Data Berhasil Disimpan");
        }
    }//GEN-LAST:event_bsimpanMouseClicked

    private void beditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseClicked
        // TODO add your handling code here:
        if(tuser.getText().isEmpty() || tnama.getText().isEmpty() || temail.getText().isEmpty() || tno.getText().isEmpty() || talamat.getText().isEmpty() || tpass.getText().isEmpty() || temail.getText().isEmpty() || tjabatan.getSelectedItem().equals("---------------Pilih Jabatan-------------")){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Terlebih Dahulu");
        }else{
            aksi.update("tbl_user", "nama = '"+tnama.getText()+"',  alamat ='"+talamat.getText()+"', email = '"+temail.getText()+"',  no_hp ='"+tno.getText()+"', jabatan = '"+tjabatan.getSelectedItem()+"'", "kd_user = '"+tabmodel.getValueAt(tbl_user.getSelectedRow(), 1)+"'");
            refresh();
//            String sql = "UPDATE tbl_user SET nama = '"+tnama.getText()+"',  alamat ='"+talamat.getText()+"', email = '"+temail.getText()+"',  no_hp ='"+tno.getText()+"', jabatan = '"+tjabatan.getSelectedItem()+"' WHERE kd_user = '"+tabmodel.getValueAt(tbl_user.getSelectedRow(), 1)+"'";
//            aksi(sql, "Data Berhasil Diubah");
        }
    }//GEN-LAST:event_beditMouseClicked

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_hideMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void tnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_TAB) ))){
            evt.consume();
        }
    }//GEN-LAST:event_tnoKeyTyped

    private void tuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        session=args[0];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bedit;
    private javax.swing.JPanel bhapus;
    private javax.swing.JPanel breset;
    private javax.swing.JPanel bsimpan;
    private javax.swing.JPanel close;
    private javax.swing.JPanel hide;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea talamat;
    private javax.swing.JTable tbl_user;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField temail;
    private javax.swing.JComboBox tjabatan;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tno;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
