/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author JamilahLKM
 */
public class admin_profil extends javax.swing.JFrame {
    
    public Statement st;
    public ResultSet rs;
    public Connection cn = config.koneksi.getKoneksi();
    public static String session;
    public String kd;
    fungsi aksi = new fungsi();
    
    public void tampildata(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tbl_user WHERE username = '"+session+"' ");
            while(rs.next()){
                kd =rs.getString("kd_user");
                tuser.setText(rs.getString("username"));
                tpass.setText(rs.getString("password"));
                tnama.setText(rs.getString("nama"));
                temail.setText(rs.getString("email"));
                talamat.setText(rs.getString("alamat"));
                tno.setText(rs.getString("no_hp"));
                tjabatan.setText(rs.getString("jabatan"));   
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates new form admin_profil
     */
    public admin_profil() {
        initComponents();
        tampildata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        bubah = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tjabatan = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        tnama = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        tpass = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        tno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        hide = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(85, 153, 142));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 610, 20));

        jLabel6.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rmdnzdn");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, -1, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 710, 610, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 146, 61));
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 320, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(232, 146, 61));
        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        temail.setBackground(new java.awt.Color(85, 153, 142));
        temail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        temail.setForeground(new java.awt.Color(255, 255, 255));
        temail.setBorder(null);
        temail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                temailKeyTyped(evt);
            }
        });
        jPanel1.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 320, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 320, 10));

        bubah.setBackground(new java.awt.Color(74, 131, 122));
        bubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bubah.setEnabled(false);
        bubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bubahMouseClicked(evt);
            }
        });
        bubah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("UBAH");
        bubah.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 50));

        jPanel1.add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 320, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(232, 146, 61));
        jLabel14.setText("No Handphone");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        tjabatan.setEditable(false);
        tjabatan.setBackground(new java.awt.Color(85, 153, 142));
        tjabatan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tjabatan.setForeground(new java.awt.Color(255, 255, 255));
        tjabatan.setBorder(null);
        tjabatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tjabatanKeyTyped(evt);
            }
        });
        jPanel1.add(tjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 320, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 320, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(232, 146, 61));
        jLabel15.setText("Username");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        tuser.setEditable(false);
        tuser.setBackground(new java.awt.Color(85, 153, 142));
        tuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tuser.setForeground(new java.awt.Color(255, 255, 255));
        tuser.setBorder(null);
        tuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tuserKeyTyped(evt);
            }
        });
        jPanel1.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 320, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 320, 10));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(232, 146, 61));
        jLabel19.setText("Password");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 320, 10));

        tnama.setBackground(new java.awt.Color(85, 153, 142));
        tnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tnama.setForeground(new java.awt.Color(255, 255, 255));
        tnama.setBorder(null);
        jPanel1.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 320, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 320, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(232, 146, 61));
        jLabel10.setText("Nama");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        talamat.setBackground(new java.awt.Color(85, 153, 142));
        talamat.setColumns(20);
        talamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        talamat.setForeground(new java.awt.Color(255, 255, 255));
        talamat.setRows(5);
        talamat.setBorder(null);
        jScrollPane2.setViewportView(talamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 320, 120));

        tpass.setBackground(new java.awt.Color(85, 153, 142));
        tpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setBorder(null);
        jPanel1.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 320, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(232, 146, 61));
        jLabel20.setText("Jabatan");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 320, 10));

        tno.setBackground(new java.awt.Color(85, 153, 142));
        tno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tno.setForeground(new java.awt.Color(255, 255, 255));
        tno.setBorder(null);
        tno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnoKeyTyped(evt);
            }
        });
        jPanel1.add(tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 320, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1370, -1));

        jPanel2.setBackground(new java.awt.Color(74, 131, 122));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FORM UBAH DATA DIRI");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 40));

        hide.setBackground(new java.awt.Color(74, 131, 122));
        hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        hide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kembali");
        hide.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        getContentPane().add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 130, 40));

        close.setBackground(new java.awt.Color(74, 131, 122));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        close.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 50, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temailKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_temailKeyTyped

    private void bubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bubahMouseClicked
        // TODO add your handling code here:
        if(tuser.getText().isEmpty() || tnama.getText().isEmpty() || temail.getText().isEmpty() || tjabatan.getText().isEmpty() || talamat.getText().isEmpty() || tpass.getText().isEmpty() || tno.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Terlebih Dahulu");
        }else{
            aksi.update("tbl_user", "nama = '"+tnama.getText()+"', password = '"+tpass.getText()+"',  alamat ='"+talamat.getText()+"', email = '"+temail.getText()+"',  no_hp ='"+tno.getText()+"', jabatan = '"+tjabatan.getText()+"'", "kd_user = '"+kd+"'");
            tampildata();
            //            String sql = "UPDATE tbl_user SET nama = '"+tnama.getText()+"',  alamat ='"+talamat.getText()+"', email = '"+temail.getText()+"',  no_hp ='"+tno.getText()+"', jabatan = '"+tjabatan.getSelectedItem()+"' WHERE kd_user = '"+tabmodel.getValueAt(tbl_user.getSelectedRow(), 1)+"'";
            //            aksi(sql, "Data Berhasil Diubah");
        }
    }//GEN-LAST:event_bubahMouseClicked

    private void tjabatanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tjabatanKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tjabatanKeyTyped

    private void tuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserKeyTyped

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_hideMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void tnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_TAB) ))){
            evt.consume();
        }
    }//GEN-LAST:event_tnoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        session=args[0];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bubah;
    private javax.swing.JPanel close;
    private javax.swing.JPanel hide;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea talamat;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tjabatan;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tno;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
