/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author zidun
 */
public class admin_sopir extends javax.swing.JFrame {
     public Statement st;
    public ResultSet rs;
    public Connection cn = config.koneksi.getKoneksi();
    public DefaultTableModel tabmodel;
    public String session;
    fungsi aksi = new fungsi();
    
    public void judul(){
        Object[] judul ={"No.","Kode Sopir","Nama","Alamat","No.HP","No.SIM","Username","Password","Status"};
        tabmodel = new DefaultTableModel(null,judul);
        tbl_sopir.setModel(tabmodel);
    }
    
    
    public void tampildata(){
        try {
            int no = 1;
            st = cn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tbl_sopir");
            while (rs.next()) {
               int b = no++;
                    Object[] data = {
                        b,
                        rs.getString("kd_sopir"),
                        rs.getString("nama"),
                        rs.getString("alamat"),
                        rs.getString("no_hp"),
                        rs.getString("no_sim"),
                        rs.getString("username"),
                        rs.getString("password"),
                        rs.getString("status_sopir")
                    };
                    tabmodel.addRow(data);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
     public void reset(){
        tnama.setText("");
        talamat.setText("");
        tnosim.setText("");
        tno.setText("");
        tpass.setText("");
        tuser.setText("");
        tuser.setEditable(true);
        bhapus.setVisible(false);
        bedit.setVisible(false);
        bsimpan.setVisible(true);
        breset.setVisible(true);
        tnama.requestFocus();
        autokode();
    }
     
    
//    public void aksi(String sql, String pesan){
//        try {
//            st = cn.createStatement();
//            st.executeUpdate(sql);
//            JOptionPane.showMessageDialog(null, pesan);
//            tampildata();
//            reset();
//            autokode();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
     
     public void refresh(){
         tampildata();
         reset();
         autokode();
     }
    
    public void autokode(){
        try {
            String tampilkode = "";
            Date date = new Date();
            SimpleDateFormat format = new SimpleDateFormat("YMM");
            String tgl = format.format(date);
            st = cn.createStatement();
            rs = st.executeQuery("SELECT MAX(RIGHT(kd_sopir,3)) FROM tbl_sopir WHERE kd_sopir LIKE '%"+tgl+"%' order by kd_sopir DESC limit 0,1");
            if(rs.next()){
                int no = rs.getInt(1)+1;
                if (no < 10) {
                    tampilkode = "SPR"+tgl+"00"+String.valueOf(no);
                } else if(no > 9 && no <= 99) {
                     tampilkode = "SPR"+tgl+"0"+String.valueOf(no);
                }else{
                    tampilkode = "SPR"+tgl+String.valueOf(no);
                }
                tkode.setText(tampilkode);
            }else{
                tkode.setText("SPR"+tgl+"001");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * Creates new form admin_sopir
     */
    public admin_sopir() {
        initComponents();
        judul();
        tampildata();
        reset();
        autokode();
        tnama.requestFocus();
        bhapus.setVisible(false);
        bedit.setVisible(false);
        bsimpan.setVisible(true);
        breset.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        hide = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        tnosim = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        tcari = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sopir = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        bhapus = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        breset = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        bedit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tno = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        tnama = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        tpass = new javax.swing.JPasswordField();
        tkode = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(74, 131, 122));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FORM INPUT SOPIR");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 40));

        hide.setBackground(new java.awt.Color(74, 131, 122));
        hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        hide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kembali");
        hide.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        getContentPane().add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 130, 40));

        close.setBackground(new java.awt.Color(74, 131, 122));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        close.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 50, 40));

        jPanel1.setBackground(new java.awt.Color(85, 153, 142));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 610, 20));

        jLabel6.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rmdnzdn");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 690, -1, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 710, 610, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 146, 61));
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 320, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(232, 146, 61));
        jLabel11.setText("No SIM");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        tnosim.setBackground(new java.awt.Color(85, 153, 142));
        tnosim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tnosim.setForeground(new java.awt.Color(255, 255, 255));
        tnosim.setBorder(null);
        tnosim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnosimKeyTyped(evt);
            }
        });
        jPanel1.add(tnosim, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 320, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 320, 10));

        tcari.setBackground(new java.awt.Color(85, 153, 142));
        tcari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tcari.setForeground(new java.awt.Color(255, 255, 255));
        tcari.setBorder(null);
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });
        jPanel1.add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 560, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(232, 146, 61));
        jLabel12.setText("Pencarian");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 560, 20));

        tbl_sopir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sopir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sopirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sopir);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 690, 420));

        jPanel6.setBackground(new java.awt.Color(74, 131, 122));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("REFRESH");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 120, 40));

        bhapus.setBackground(new java.awt.Color(74, 131, 122));
        bhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bhapus.setEnabled(false);
        bhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bhapusMouseClicked(evt);
            }
        });
        bhapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("HAPUS");
        bhapus.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 50));

        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 320, -1));

        breset.setBackground(new java.awt.Color(74, 131, 122));
        breset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        breset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bresetMouseClicked(evt);
            }
        });
        breset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("RESET");
        breset.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 50));

        jPanel1.add(breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 320, -1));

        bsimpan.setBackground(new java.awt.Color(74, 131, 122));
        bsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsimpanMouseClicked(evt);
            }
        });
        bsimpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SIMPAN");
        bsimpan.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 50));

        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 320, 50));

        bedit.setBackground(new java.awt.Color(74, 131, 122));
        bedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bedit.setEnabled(false);
        bedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beditMouseClicked(evt);
            }
        });
        bedit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("UBAH");
        bedit.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 50));

        jPanel1.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 320, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(232, 146, 61));
        jLabel14.setText("No Handphone");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        tno.setBackground(new java.awt.Color(85, 153, 142));
        tno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tno.setForeground(new java.awt.Color(255, 255, 255));
        tno.setBorder(null);
        tno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnoKeyTyped(evt);
            }
        });
        jPanel1.add(tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 320, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 320, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(232, 146, 61));
        jLabel15.setText("Username");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        tuser.setBackground(new java.awt.Color(85, 153, 142));
        tuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tuser.setForeground(new java.awt.Color(255, 255, 255));
        tuser.setBorder(null);
        tuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tuserKeyTyped(evt);
            }
        });
        jPanel1.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 320, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 320, 10));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(232, 146, 61));
        jLabel19.setText("Password");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 320, 10));

        tnama.setBackground(new java.awt.Color(85, 153, 142));
        tnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tnama.setForeground(new java.awt.Color(255, 255, 255));
        tnama.setBorder(null);
        jPanel1.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 320, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 320, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(232, 146, 61));
        jLabel10.setText("Nama");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        talamat.setBackground(new java.awt.Color(85, 153, 142));
        talamat.setColumns(20);
        talamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        talamat.setForeground(new java.awt.Color(255, 255, 255));
        talamat.setRows(5);
        talamat.setBorder(null);
        jScrollPane2.setViewportView(talamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 320, 80));

        tpass.setBackground(new java.awt.Color(85, 153, 142));
        tpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setBorder(null);
        jPanel1.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 320, 30));

        tkode.setEditable(false);
        tkode.setBackground(new java.awt.Color(85, 153, 142));
        tkode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tkode.setForeground(new java.awt.Color(255, 255, 255));
        tkode.setBorder(null);
        jPanel1.add(tkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 320, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 320, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(232, 146, 61));
        jLabel5.setText("Kode Sopir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_hideMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        // TODO add your handling code here:
        try {
            int no = 1;
            st = cn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tbl_sopir WHERE kd_sopir LIKE '%"+tcari.getText()+"%' OR password LIKE '%"+tcari.getText()+"%' OR nama LIKE '%"+tcari.getText()+"%' OR alamat LIKE '%"+tcari.getText()+"%' OR no_sim LIKE '%"+tcari.getText()+"%' OR no_hp LIKE '%"+tcari.getText()+"%' OR username LIKE '%"+tcari.getText()+"%'");
            while (rs.next()) {
               int b = no++;
                    Object[] data = {
                        b,
                        rs.getString("kd_sopir"),
                        rs.getString("nama"),
                        rs.getString("alamat"),
                        rs.getString("no_hp"),
                        rs.getString("no_sim"),
                        rs.getString("username"),
                        rs.getString("password")
                    };
                    tabmodel.addRow(data);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tcariKeyReleased

    private void tbl_sopirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sopirMouseClicked
        // TODO add your handling code here:
        tkode.setText(tabmodel.getValueAt(tbl_sopir.getSelectedRow(), 1)+"");
        tnama.setText(tabmodel.getValueAt(tbl_sopir.getSelectedRow(), 2)+"");
        tnosim.setText(tabmodel.getValueAt(tbl_sopir.getSelectedRow(), 5)+"");
        tno.setText(tabmodel.getValueAt(tbl_sopir.getSelectedRow(), 4)+"");
        tuser.setText(tabmodel.getValueAt(tbl_sopir.getSelectedRow(), 6)+"");
        tpass.setText(tabmodel.getValueAt(tbl_sopir.getSelectedRow(), 7)+"");
        talamat.setText(tabmodel.getValueAt(tbl_sopir.getSelectedRow(), 3)+"");
        tnama.requestFocus();
        tuser.setEditable(false);
        bhapus.setVisible(true);
        bedit.setVisible(true);
        bsimpan.setVisible(false);
        breset.setVisible(true);
    }//GEN-LAST:event_tbl_sopirMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        tcariKeyReleased(null);
        tcari.setText("");
        tampildata();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void bhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhapusMouseClicked
        // TODO add your handling code here:
        int jawab = 0;
        if((jawab = JOptionPane.showConfirmDialog(null, "Anda yakin kan menghapus data ini ?","Konfirmasi", JOptionPane.YES_NO_OPTION))==0){
            aksi.hapus("tbl_sopir", "kd_sopir = '"+tkode.getText()+"'");
            refresh();
//            String sql = "DELETE FROM tbl_sopir WHERE kd_sopir = '"+tkode.getText()+"'";
//            aksi(sql,"Data Berhasil Dihapus");
        }
    }//GEN-LAST:event_bhapusMouseClicked

    private void bresetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bresetMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bresetMouseClicked

    private void bsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsimpanMouseClicked
        // TODO add your handling code here:
        if(tkode.getText().isEmpty() || tuser.getText().isEmpty() || tnama.getText().isEmpty() || tnosim.getText().isEmpty() || tno.getText().isEmpty() || talamat.getText().isEmpty() || tpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Terlebih Dahulu");
        } else {
            aksi.simpan("tbl_sopir", "'"+tkode.getText()+"','"+tnama.getText()+"','"+talamat.getText()+"','"+tno.getText()+"','"+tnosim.getText()+"','"+tuser.getText()+"','"+tpass.getText()+"','sopir','tersedia'");
            refresh();
//            String sql = "INSERT INTO tbl_sopir VALUES('"+tkode.getText()+"','"+tnama.getText()+"','"+talamat.getText()+"','"+tno.getText()+"','"+tnosim.getText()+"','"+tuser.getText()+"','"+tpass.getText()+"','sopir','tersedia')";
//            aksi(sql,"Data Berhasil Disimpan");
        }
    }//GEN-LAST:event_bsimpanMouseClicked

    private void beditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseClicked
        // TODO add your handling code here:
         if(tkode.getText().isEmpty() || tuser.getText().isEmpty() || tnama.getText().isEmpty() || tnosim.getText().isEmpty() || tno.getText().isEmpty() || talamat.getText().isEmpty() || tpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Terlebih Dahulu");
        }else{
             aksi.update("tbl_sopir", "nama = '"+tnama.getText()+"',  alamat ='"+talamat.getText()+"', no_sim = '"+tnosim.getText()+"',  no_hp ='"+tno.getText()+"', password = '"+tpass.getText()+"'", "kd_sopir = '"+tkode.getText()+"'");
             refresh();
//            String sql = "UPDATE tbl_sopir SET nama = '"+tnama.getText()+"',  alamat ='"+talamat.getText()+"', no_sim = '"+tnosim.getText()+"',  no_hp ='"+tno.getText()+"', password = '"+tpass.getText()+"' WHERE kd_sopir = '"+tkode.getText()+"'";
//            aksi(sql, "Data Berhasil Diubah");
        }
    }//GEN-LAST:event_beditMouseClicked

    private void tnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_TAB) ))){
            evt.consume();
        }
    }//GEN-LAST:event_tnoKeyTyped

    private void tuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserKeyTyped

    private void tnosimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnosimKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_TAB) ))){
            evt.consume();
        }
    }//GEN-LAST:event_tnosimKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_sopir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_sopir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_sopir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_sopir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_sopir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bedit;
    private javax.swing.JPanel bhapus;
    private javax.swing.JPanel breset;
    private javax.swing.JPanel bsimpan;
    private javax.swing.JPanel close;
    private javax.swing.JPanel hide;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea talamat;
    private javax.swing.JTable tbl_sopir;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tkode;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tno;
    private javax.swing.JTextField tnosim;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
