/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author zidun
 */
public class login extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public Connection cn = config.koneksi.getKoneksi();
    /**z
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JPanel();
        hide1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        tpass = new javax.swing.JPasswordField();
        jSeparator11 = new javax.swing.JSeparator();
        blogin = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(74, 131, 122));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FORM LOGIN ADMIN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 40));

        close.setBackground(new java.awt.Color(74, 131, 122));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        close.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 50, 40));

        bsimpan.setBackground(new java.awt.Color(85, 153, 142));
        bsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsimpanMouseClicked(evt);
            }
        });
        bsimpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hide1.setBackground(new java.awt.Color(74, 131, 122));
        hide1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide1MouseClicked(evt);
            }
        });
        hide1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(232, 146, 61));
        jLabel15.setText("Username");
        hide1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        tuser.setBackground(new java.awt.Color(74, 131, 122));
        tuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tuser.setForeground(new java.awt.Color(255, 255, 255));
        tuser.setBorder(null);
        tuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tuserKeyTyped(evt);
            }
        });
        hide1.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 320, 30));
        hide1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 320, 10));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(232, 146, 61));
        jLabel19.setText("Password");
        hide1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        tpass.setBackground(new java.awt.Color(74, 131, 122));
        tpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tpass.setForeground(new java.awt.Color(255, 255, 255));
        tpass.setBorder(null);
        hide1.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 320, 30));
        hide1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 320, 10));

        blogin.setBackground(new java.awt.Color(85, 153, 142));
        blogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bloginMouseClicked(evt);
            }
        });
        blogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("LOGIN");
        blogin.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 50));

        hide1.add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 320, 50));

        bsimpan.add(hide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 860, 420));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 75)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PO. SETIA BHAKTI");
        bsimpan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JL. Melawai Raya No.70 Jakarta Pusat");
        bsimpan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1380, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsimpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void hide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hide1MouseClicked

    private void tuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserKeyTyped

    private void bloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloginMouseClicked
        // TODO add your handling code here:
        if(tuser.getText().isEmpty() || tpass.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "LENGKAPi DATA !");
            tuser.requestFocus();
        }else{
            try {
                st =cn.createStatement();
                rs = st.executeQuery("SELECT * FROM tbl_user WHERE jabatan ='admin'");
                String user,pass;
                int a = 0;
                while (rs.next()) {                    
                    user = rs.getString("username");
                    pass = rs.getString("password");
                    if(tuser.getText().equals(user) && tpass.getText().equals(pass)){
                        JOptionPane.showMessageDialog(null, "LOGIN BERHASIL !");
                        String tmp_id[] = new String[1];
                        tmp_id[0] = tuser.getText();
                        utama_admin.main(tmp_id);
                        this.setVisible(false);
                        a++;
                    }
                }
                if(a == 0){
                    JOptionPane.showMessageDialog(null, "USERNAME atau PASSWORD Anda salah");
                    tuser.setText("");
                    tuser.requestFocus();
                    tpass.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_bloginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blogin;
    private javax.swing.JPanel bsimpan;
    private javax.swing.JPanel close;
    private javax.swing.JPanel hide1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
